# Generated by Django 4.2.13 on 2024-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biden_count', models.IntegerField(default=0)),
                ('trump_count', models.IntegerField(default=0)),
            ],
        ),
    ]
