# Generated by Django 4.2.13 on 2024-05-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_advice', models.TextField(max_length=3000)),
                ('target_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaryapp.diaryapp')),
            ],
        ),
    ]
