# Generated by Django 4.2.13 on 2024-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_diaryapp_analysis_alter_diaryapp_gpt_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryapp',
            name='sleep_hour',
            field=models.FloatField(default=0.0, max_length=3000),
        ),
    ]
